### ISSUE TITLE
jira export is failing

### ISSUE THREAD

**Issue by cpadala2050** [solidify/jira-azuredevops-migrator#1054]
export command is failing with this error
[I][07:25:18] Connecting to Jira...
[I][07:25:18] Retrieving Jira fields...
[I][07:25:19] Retrieving Jira link types...
[E][07:25:19] Failed to get item count using query: 'project="SCRUM"'
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'SCRUM' does not exist for the field 'project'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
---> (Inner Exception #0) System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'SCRUM' does not exist for the field 'project'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()<---
: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
[I][07:25:19] Export started. Selecting 0 items.
[W][07:25:20] Epic link field missing for config field 'Epic Link'.
[W][07:25:20] Sprint link field missing for config field 'Sprint'.
[I][07:25:20] Initializing Jira field mapping...
[W][07:25:20] Could not find the field id for 'Sprint', please check the field mapping!
[W][07:25:20] Could not find the field id for 'Story Points', please check the field mapping!
[E][07:25:20] Failed to retrieve issues
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'SCRUM' does not exist for the field 'project'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.<EnumerateIssues>d__30.MoveNext()
---> (Inner Exception #0) System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'SCRUM' does not exist for the field 'project'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()<---
: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.<EnumerateIssues>d__30.MoveNext()
[I][07:25:20] Export complete. Exported 0 items (2 errors, 4 warnings) in 00:00:02.

export command used: jira-export -u somevalue@duck.domain -p somepassword --url https://mydomain.atlassian.net/ --config config-scrum.json --force

**Tool version**
 - Version of the[jira-azuredevops-migrator-3.0.422.zip

**Attachments**

Please attach the following files:

- config.json
- jira-export-log.txt
- wi-import-log.txt

**Screenshots**
[jira-export-log-240615-073932.txt](https://github.com/user-attachments/files/15846100/jira-export-log-240615-073932.txt)
[config-scrum.json](https://github.com/user-attachments/files/15846101/config-scrum.json)

**Comment by cpadala2050** [comment]
It is similar issue to [jira-azuredevops-migrator-3.0.422.zip](https://github.com/solidify/jira-azuredevops-migrator/releases/download/v3.0.422/jira-azuredevops-migrator-3.0.422.zip) , I have recently created new jira account and my user is admin user but still same issue

**Comment by cpadala2050** [comment]
It worked with access token
