### ISSUE TITLE
Jira export - Unexpected migration error. [System.InvalidCastException]

### ISSUE THREAD

**Issue by smorrisonk** [solidify/jira-azuredevops-migrator#1056]
**Describe the problem**

I getting an error when trying to export issues from Jira;

Unexpected migration error.
[System.InvalidCastException] System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.

From my research it could have to do with my local json-file failing to parse(?) but I need help on how to solve the issue.

**To Reproduce**

The command I'm running (on Mackbook, using Wine to run the file) is "wine jira-export.exe -u myUerEmail -p myJiraToken --url https://jiraWorkspace.atlassian.net --config config-basic.json --force"

**Tool version**
jira-azuredevops-migrator-3.0.426

**Attachments**

Please attach the following files:
[config-basic.json](https://github.com/user-attachments/files/16142511/config-basic.json)
[error-message.txt](https://github.com/user-attachments/files/16142519/error-message.txt)

**Comment by Alexander-Hjelm** [comment]
The exception is raised inside the getter for `EpicParent`, on `JiraItem.cs`:

https://github.com/solidify/jira-azuredevops-migrator/blob/c52b270468e7e7f285f4ec5046a7719d392b4720/src/WorkItemMigrator/JiraExport/JiraItem.cs#L596-L605

This in turn calls the `ExValue` extension method on a `JObject`, when `ExValue` is only defined for the type `JToken`:

https://github.com/solidify/jira-azuredevops-migrator/blob/c52b270468e7e7f285f4ec5046a7719d392b4720/src/WorkItemMigrator/Migration.Common/JsonExtensions.cs#L9-L23

Do you have any previous experience of getting the JiraExporter to work on mac? We do not officially support MacOS yet, and I would recommend running the CLI in a Windows VM instead.

**Comment by jbparker** [comment]
Windows user here running into the same exception:

```
[System.InvalidCastException] System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at Migration.Common.JsonExtensions.ExValue[T](JToken token, String path)
   at JiraExport.JiraItem.get_EpicParent()
   at JiraExport.JiraProvider.<EnumerateIssues>d__30.MoveNext()
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical):
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at Migration.Common.JsonExtensions.ExValue[T](JToken token, String path)
   at JiraExport.JiraItem.get_EpicParent()
   at JiraExport.JiraProvider.<EnumerateIssues>d__30.MoveNext()
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
```

**Comment by jbparker** [comment]
Looks like it is related to this: [Upcoming changes: 'epic-link' replaced with 'parent'](https://support.atlassian.com/jira-software-cloud/docs/upcoming-changes-epic-link-replaced-with-parent/)

Can see a demo of the new complex object `parent` here: [.NET fiddle](https://dotnetfiddle.net/x14gAH)

That said, there is usually another custom field in the payload that represents the old `epic-link` field that can be used for instead of the `parent` field.

**Comment by Alexander-Hjelm** [comment]
@jbparker @smorrisonk 
Ok, my bad! :)

Do you have any more details on how to create/modify a Jira issue in order to reproduce this error message? Does it always happen when you add an epic link to an issue?

Any issue histories if available would be helpful!

**Comment by FuntwoCode** [comment]
@Alexander-Hjelm Is there an update on this issue? I run into the same problem.

It works when exporting Jira Issues that aren't in a child relationship. But if Issues are a child, e.g., an epic, I get the same error message as jbparker.

**Comment by Alexander-Hjelm** [comment]
@FuntwoCode, repro steps were requested but never provided. Eventually the issue was closed due to lack of activity. Please reopen the issue or create a new issue and provide thorough repro steps if the problem persists.

**Comment by ThomasVer** [comment]
@Alexander-Hjelm I am having the same issue.

For testing purposes, I created a new Jira issue with no content and no parent. The export succeeds for the issue.
Added a parent to the issue and ran the export again, I get the same error as @jbparker mentioned:
```
[System.InvalidCastException] System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Migration.Common.JsonExtensions.ExValue[T](JToken token, String path)
   at JiraExport.JiraItem.get_EpicParent()
   at JiraExport.JiraProvider.EnumerateIssues(String jql, HashSet`1 skipList, DownloadOptions downloadOptions)+MoveNext()
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical): 
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Migration.Common.JsonExtensions.ExValue[T](JToken token, String path)
   at JiraExport.JiraItem.get_EpicParent()
   at JiraExport.JiraProvider.EnumerateIssues(String jql, HashSet`1 skipList, DownloadOptions downloadOptions)+MoveNext()
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
```

Attached my config as a reference

[config-scrum.json](https://github.com/user-attachments/files/22120006/config-scrum.json)

**Comment by Alexander-Hjelm** [comment]
Here is the line which is throwing the exception:

https://github.com/solidify/jira-azuredevops-migrator/blob/a88584d31878170d6d488395a840b412aa225ca6/src/WorkItemMigrator/JiraExport/JiraItem.cs#L597

Seems like `RemoteIssue` cannot be parsed as a JToken?

**Comment by ThomasVer** [comment]
Yes, it appears so.
I've tried leaving the setting `epic-link-field` blank in my config blank (and fall back to the `Parent` property), but then I get this error.
```
[System.ArgumentNullException] System.ArgumentNullException: Value cannot be null. (Parameter 'field')
   at JiraExport.LinkMapperUtils.AddRemoveSingleLink(JiraRevision r, List`1 links, String field, String type, ConfigJson config)
   at JiraExport.JiraMapper.MapLinks(JiraRevision r)
   at JiraExport.JiraMapper.MapRevision(JiraRevision r)
   at JiraExport.JiraMapper.<>c__DisplayClass6_0.<Map>b__2(JiraRevision r)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at JiraExport.JiraMapper.Map(JiraItem issue)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical): 
   at JiraExport.LinkMapperUtils.AddRemoveSingleLink(JiraRevision r, List`1 links, String field, String type, ConfigJson config)
   at JiraExport.JiraMapper.MapLinks(JiraRevision r)
   at JiraExport.JiraMapper.MapRevision(JiraRevision r)
   at JiraExport.JiraMapper.<>c__DisplayClass6_0.<Map>b__2(JiraRevision r)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at JiraExport.JiraMapper.Map(JiraItem issue)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
```

**Comment by ThomasVer** [comment]
@Alexander-Hjelm Any update on this? Should I create a new issue?

**Comment by ThomasVer** [comment]
I think this is the same bug as described here:
https://github.com/solidify/jira-azuredevops-migrator/issues/1117
