### ISSUE TITLE
Jira connectivity Issue while migrating Atlassian Jira Cloud to ADO

### ISSUE THREAD

**Issue by vani760** [solidify/jira-azuredevops-migrator#1078]
Hi team,

we are migrating board from Atlassian jira cloud to ADO  and we are using solidify migrator tool for this migration.
we have followed all the necessary steps which is mentioned in the document. but when we run export command i am getting Authentication issue.

Migrator tool link: https://solidify.dev/blog/jira-azure-devops-migration
Export Command: jira-export -u <user mail id> -p <API Token> --url https://acn-ix-genai.atlassian.net/jira --config config-scrum.json
Version of the jira-azuredevops-migrator tool: jira-azuredevops-migrator-3.0.486>
 
error:

[E][17:15:25] Failed to retrieve fields from Jira (Response was not recognized as JSON). This usually indicates a problem with authentication or authorization. Check your Jira credentials and permissions.
[System.AggregateException] System.AggregateException: One or more errors occurred. (Error Message: The SSL connection could not be established, see inner exception.)
 ---> System.InvalidOperationException: Error Message: The SSL connection could not be established, see inner exception.
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.ExecuteRequestAsync(Method method, String resource, Object requestBody, CancellationToken token)
   at Atlassian.Jira.Remote.JiraRestClient.ExecuteRequestAsync[T](Method method, String resource, Object requestBody, CancellationToken token)
   at Atlassian.Jira.Remote.IssueFieldService.GetCustomFieldsAsync(CancellationToken token)

**Comment by Alexander-Hjelm** [comment]
Hello @vani760 !

Please see the following troubleshooting guide for issues with authentication against the Jira Rest API: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#2-why-i-am-getting-unauthorized-exception-when-running-the-export

If that does not help, let me know and let us take it from there.

**Comment by vani760** [comment]
Hello @Alexander-Hjelm 
i have tried bt creating new API token and with other teammate credential also but still we are facing same issue.

we have tested with Curl command and it is working fine and we can import issue from Jira... but with Export command we are facing issue. can we please connect once to know more

**Comment by Alexander-Hjelm** [comment]
For Jira Cloud, it usually works to put your full email as the username (-u) and your Jira API token as the password (-p).

Can you please share the Authorization header for the curl command that worked?

**Comment by vani760** [comment]
curl -D- -u <user email id>:<API Token> "Content-Type: application/json" "https://acn-ix-genai.atlasian.net/rest/api/2/search?jql=issuekey=GENAIASSET-2128" -o C:\temp\JiraExport\exported_data.json

with user mail id then API token we used in curl command and given specific issue Id to export and save that file in exportet_data. json file

**Comment by vani760** [comment]
can we connect through call please if possible

**Comment by Alexander-Hjelm** [comment]
Live support is only available through purchase of Professional Service Hours.

Your curl command is working because you are already authenticated via Windows Credential Manager or AD.

Is it possible to set up the same request in Postman or via a client which is not already authenticated?

**Comment by vani760** [comment]
Live support is only available through purchase of Professional Service Hours. means how to purchase .. can you please let me know the details?

**Comment by vani760** [comment]
Hi,
you can close this issue.. Thank you for your support
