### ISSUE TITLE
Issue in Curl Command while preforming the Jira to ADO Migration.

### ISSUE THREAD

**Issue by harishtc** [solidify/jira-azuredevops-migrator#1080]
Hi Team,

We are migrating boards from Atlassian Jira software cloud to Azure DevOps. For this we are using the Solidify migration tool.

We have followed all the necessary steps mentioned in the document, as I have Jira admin, and I created a new API token. We have run the Jira export command and are getting the below error.
Could you please help us to fix it?.

Regards,
Harish.
[Jira Exporter v0.docx](https://github.com/user-attachments/files/18124821/Jira.Exporter.v0.docx)

**Comment by Alexander-Hjelm** [comment]
> Oops, you&#39;ve found a dead link. - JIRA

Looks ilke the Request URL is invalid.

Is the Jira URL and source project name/key correct?

If facing authentication issues, see the troubleshooting guide with answers to common problems here: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md

**Comment by harishtc** [comment]
Hi Alex,

Thanks for your response.
I've changed the Jira URL and project key (Previously given project name). Now auth issue is fixed i believe. now got below error.

[I][11:29:20] Connecting to Jira...
[I][11:29:20] Retrieving Jira fields...
[I][11:29:21] Retrieving Jira link types...
[I][11:29:22] Export started. Selecting 1 items.
[W][11:29:23] Epic link field missing for config field 'https://xxxxxxxx.atlassian.net/browse/TCM-46'.
[I][11:29:23] Initializing Jira field mapping...
[I][11:29:23] Processing 1/1 - 'TCM-51'.
[W][11:29:25] Could not find user 'user@xxxxxxx.com' identity in user map. Using original identity 'user@xxxxxx.com'.
[W][11:29:25] Multiple fields found for comment. Selecting customfield_10200.
[W][11:29:25] Multiple fields found for description. Selecting description.
[E][11:29:25] Unexpected migration error.
[System.ArgumentNullException] System.ArgumentNullException: Value cannot be null. (Parameter 'field')
   at JiraExport.LinkMapperUtils.AddRemoveSingleLink(JiraRevision r, List`1 links, String field, String type, ConfigJson config)
   at JiraExport.JiraMapper.MapLinks(JiraRevision r)
   at JiraExport.JiraMapper.MapRevision(JiraRevision r)
   at JiraExport.JiraMapper.<>c__DisplayClass6_0.<Map>b__2(JiraRevision r)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at JiraExport.JiraMapper.Map(JiraItem issue)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical): 
   at JiraExport.LinkMapperUtils.AddRemoveSingleLink(JiraRevision r, List`1 links, String field, String type, ConfigJson config)
   at JiraExport.JiraMapper.MapLinks(JiraRevision r)
   at JiraExport.JiraMapper.MapRevision(JiraRevision r)
   at JiraExport.JiraMapper.<>c__DisplayClass6_0.<Map>b__2(JiraRevision r)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at JiraExport.JiraMapper.Map(JiraItem issue)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
[I][11:29:25] Export complete. Exported 0 items (1 errors, 4 warnings) in 00:00:05.

**Comment by Alexander-Hjelm** [comment]
Ok! What is the value of EpicLinkField in your config?

**Comment by harishtc** [comment]
Alex, its working now. i'm able to export the request i want.
Can you please put this request onhold for next 2days, so i can reach out to you incase of
