### ISSUE TITLE
Incorrect URI for REST call to retrieve changelog records

### ISSUE THREAD

**Issue by Jura** [solidify/jira-azuredevops-migrator#13]
Jira export tool fails to process issues with the following stack trace:
```
[l:D][d:17:05:56] Connecting to Jira...
[l:I][d:17:05:56] Connected to Jira.
[l:I][d:17:05:56] Gathering project info...
[l:I][d:17:05:57] Custom field cache set up.
[l:I][d:17:05:57] Custom parsers set up.
[l:I][d:17:05:57] Link types cache set up.
[l:I][d:17:05:57] Processing issues...
[l:D][d:17:05:57] Downloaded [issue ID]
[l:E][d:17:05:57] Unexpected error: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 404. Response Content: {"message":"null for uri: https://[jira server]/rest/api/2/issue/[issue ID]/changelog?maxResults=100&startAt=0","status-code":404}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.<DownloadChangelog>d__18.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at JiraExport.JiraItem.BuildRevisions(JiraItem jiraItem, JiraProvider jiraProvider)
   at JiraExport.JiraItem.CreateFromRest(String issueKey, JiraProvider jiraProvider)
   at JiraExport.JiraProvider.ProcessItem(String issueKey, HashSet`1 skipList, String successMessage)
   at JiraExport.JiraProvider.<EnumerateIssues>d__17.MoveNext()
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh)
```
According to the [documentation](https://docs.atlassian.com/software/jira/docs/api/REST/7.13.0/#api/2/issue)  there is no "/changelog" endpoint and it should be referenced as https://[jira server]/rest/api/2/issue/[issue ID]**?expand=changelog**&maxResults=100&startAt=0 instead.

I've tested this construction and amended URI returns expected results

tested platform: Jira Server v7.12.2

**Comment by Jura** [comment]
@pliljecrantz it's a pretty easy fix, do you want me to create PR for it?

**Comment by MOlausson** [comment]
@Jura get to get input so feel free to make the changes and submit a PR.

**Comment by MOlausson** [comment]
Thanks for your contribution @Jura. We've integrated the fix in [R2.0.10](https://github.com/solidify/jira-azuredevops-migrator/releases/tag/v2.0.10).
