### ISSUE TITLE
Unable to extract Jira comments

### ISSUE THREAD

**Issue by strn9r** [solidify/jira-azuredevops-migrator#182]
Hi,

When exporting items from Jira the tool crashes with the exception:

**Could not convert string to DateTime: Today 11:58 AM**

ONLY in case there are comments in Jira item. If there is no any comment in Jira item then it works fine.
Exception details:
`[E][12:46:53] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> Newtonsoft.Json.JsonReaderException: Could not convert string to DateTime: Today 11:58 AM. Path '[0].created', line 32, position 31.
   at Newtonsoft.Json.JsonReader.ReadDateTimeString(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsDateTime()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Atlassian.Jira.Remote.IssueService.<GetCommentsAsync>d__45.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraItem.BuildCommentRevisions(JiraItem jiraItem, JiraProvider jiraProvider)
   at JiraExport.JiraItem.BuildRevisions(JiraItem jiraItem, JiraProvider jiraProvider)
   at JiraExport.JiraItem.CreateFromRest(String issueKey, JiraProvider jiraProvider)
   at JiraExport.JiraProvider.<EnumerateIssues>d__21.MoveNext()
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh)
---> (Inner Exception #0) Newtonsoft.Json.JsonReaderException: Could not convert string to DateTime: Today 11:58 AM. Path '[0].created', line 32, position 31.
   at Newtonsoft.Json.JsonReader.ReadDateTimeString(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsDateTime()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Atlassian.Jira.Remote.IssueService.<GetCommentsAsync>d__45.MoveNext()<---
: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraItem.BuildCommentRevisions(JiraItem jiraItem, JiraProvider jiraProvider)
   at JiraExport.JiraItem.BuildRevisions(JiraItem jiraItem, JiraProvider jiraProvider)
   at JiraExport.JiraItem.CreateFromRest(String issueKey, JiraProvider jiraProvider)
   at JiraExport.JiraProvider.<EnumerateIssues>d__21.MoveNext()
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh)`

Assuming it can be due to the fact that our Jira is configured to display date & time in such format: Today 11:58 AM. And the tool can't properly convert this format to DATETIME.
Theoretically it can be fixed by modifying Jira settings, but unfortunately it won't be as it affects all Jira projects on the same Jira instance. Thus our Jira admins refused to do that.

Could you please advise what can be done to fix or workaround this issue?

Thanks.

**Comment by strn9r** [comment]
on Jira page the date and time format are displayed in the following way:

![image](https://user-images.githubusercontent.com/52602711/74424333-cbbacd00-4e62-11ea-8429-fe0988694ffc.png)

in code it looks like this:
![image](https://user-images.githubusercontent.com/52602711/74424256-a62dc380-4e62-11ea-829c-90186b61ed7d.png)

**Comment by strn9r** [comment]
the part of the config file where comments are configured:
	  //export the Jira field "Comments" to the AzureDevops "Discussion"
	  {
		"source": "comment",
		"target": "System.History",
		"mapper": "MapRendered"
	  },

**Comment by strn9r** [comment]
@madkoo could you please check my post above and let me know the reason why it is not working or at least how i can workaround the issue? Thanks.

**Comment by madkoo** [comment]
@strn9r thank you for the input, we will investigate this.

**Comment by madkoo** [comment]
@strn9r can you elaborate whether you added a comment "Today 10:36 AM" as text or in a special way?

**Comment by strn9r** [comment]
@madkoo a comment is added as a plain text. but the way how Jira displays it it is up for Jira settings i believe. For example i've just added a new comment, please see:

![image](https://user-images.githubusercontent.com/52602711/74654305-15752180-519b-11ea-97e0-d67e3d4bfd9d.png)

a few seconds ago, then in a minute it will be a minute ago, then Yesterday or another day, and so on

**Comment by strn9r** [comment]
I believe Jira displays time in the same manner as Github does, for example my comment 4 minutes ago.
![image](https://user-images.githubusercontent.com/52602711/74654684-ed39f280-519b-11ea-94cc-e1b97f477c75.png)

**Comment by madkoo** [comment]
@strn9r  can you provide me the format you are using? Trying to reproduce this issue with no success, the tool is working as expected. eg Exported Item with the following comment  - 
![image](https://user-images.githubusercontent.com/1208114/74656089-28392780-5196-11ea-8031-7686dce6e065.png)
The export works, having the same comment mapping configuration as you.

**Comment by strn9r** [comment]
@madkoo how can i provide you the format ? the format of what ?

**Comment by madkoo** [comment]
@strn9r, I apologize that I was not specific. I meant the date-time format you are using in your Jira server configuration. 
Also, did you try exporting issues that have different time in comments?

**Comment by strn9r** [comment]
@madkoo i do not know how our Jira is configured and our Jira admins do not share this info with me. so unfortunately i can't provide you such info. Know only Jira version : 6.1.4
in regards to the second question - all our items have the same format for all fields.
i just noticed that if any Jira item has at least one comment - the export doesn't work and throws this exception.
if i delete the comment, means there are no more comments in Jira item, then the export is working fine.
and from my side it is not possible to change the format of fields.

p.s. i do understand that other fields also may have date & time stamps and they work fine.
but in case of comments it doesn't .

**Comment by strn9r** [comment]
@madkoo is it enough info provided to define possible solution or workaround?
or what i can do for you additionally from my side to get progress on this ?
thanks.

**Comment by strn9r** [comment]
@madkoo could you please update me on this ? do you any additional info from me ?

**Comment by madkoo** [comment]
@strn9r , unfortunately, we were unable to reproduce this case. We have tested with Jira version 7 and issues with comments get migrated fine.
Based on that this seems to be an issue with the Jira version you are using. If possible we would suggest upgrading to a newer version and trying then.

**Comment by madkoo** [comment]
@strn9r  closing this issue due to inactivity and unable to reproduce the issue. If you still have problems then feel free to contact us directly.

**Comment by Paddl1203** [comment]
Hey, I have the same problem as @strn9r . Our Company is using JIRA V6.4.11 and I am also not able to export Jira Tickets with comments. The error-message is: Newtonsoft.Json.JsonReaderException: Could not convert string to DateTime: 16/Okt/19 1:22 PM. Path '[0].created', line 36, position 34.  When i exclude Tickets with comments in the jql-query the migration tool works fine. 
It is also not possible for me to upgrade Jira to a higher version what probably could fix the issue. 
Do you have any other ideas to fix this ? @madkoo

**Comment by jbtibor** [comment]
The error is still happening.
 'One or more errors occurred. (Could not convert string to DateTime: Friday 3:21 PM. Path '[0].created', line 32, position 31.)'

Happens for any issue with comments, regardless of when the comments were created. I tried Issues.GetCommentsAsync and Issue.GetCommentsAsync. There's nothing special in these comments, are added on the web interface.
