### ISSUE TITLE
ArgumentOutOfRangeException in JiraMapper.cs

### ISSUE THREAD

**Issue by MattCodd2** [solidify/jira-azuredevops-migrator#275]
When exporting a project that has links to a Jira project that has been renamed from a short issue key to a longer one the following exception is thrown in JiraMapper.cs

[D][13:03:23]    Mapping revision 1.
[E][13:03:23] Unexpected migration error.
[System.ArgumentOutOfRangeException] System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
  at JiraExport.JiraMapper.MapEpicChildLink(JiraRevision r, List`1 links, String field, String type)
   at JiraExport.JiraMapper.MapLinks(JiraRevision r)
   at JiraExport.JiraMapper.MapRevision(JiraRevision r)
   at JiraExport.JiraMapper.<>c__DisplayClass10_0.<Map>b__2(JiraRevision r)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at JiraExport.JiraMapper.Map(JiraItem issue)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical):
   at System.String.Substring(Int32 startIndex, Int32 length)
   at JiraExport.JiraMapper.MapEpicChildLink(JiraRevision r, List`1 links, String field, String type)
   at JiraExport.JiraMapper.MapLinks(JiraRevision r)
   at JiraExport.JiraMapper.MapRevision(JiraRevision r)
   at JiraExport.JiraMapper.<>c__DisplayClass10_0.<Map>b__2(JiraRevision r)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at JiraExport.JiraMapper.Map(JiraItem issue)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)

The code line that's causing the problem is line 228:

`                var childKeyStr = value?.ToString().Substring(r.OriginId.LastIndexOf("-", StringComparison.InvariantCultureIgnoreCase) + 1);
`

which is referencing the string length of the origin string.  Changing the code to

`                var childKeyStr = value?.ToString().Substring((value?.ToString()).LastIndexOf("-", StringComparison.InvariantCultureIgnoreCase) + 1);
`
allows the export to complete.

**Comment by madkoo** [comment]
@MattCodd2  thank you for the PR we will look into it

**Comment by Harshithagp** [comment]
in which file should we change that

**Comment by MattCodd2** [comment]
@Harshithagp In JiraMapper.cs.  The pull request contains the change

**Comment by Harshithagp** [comment]
> When exporting a project that has links to a Jira project that has been renamed from a short issue key to a longer one the following exception is thrown in JiraMapper.cs
> 
> [D][13:03:23] Mapping revision 1.
> [E][13:03:23] Unexpected migration error.
> [System.ArgumentOutOfRangeException] System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
> Parameter name: startIndex
> at System.String.Substring(Int32 startIndex, Int32 length)
> at JiraExport.JiraMapper.MapEpicChildLink(JiraRevision r, List`1 links, String field, String type) at JiraExport.JiraMapper.MapLinks(JiraRevision r) at JiraExport.JiraMapper.MapRevision(JiraRevision r) at JiraExport.JiraMapper.<>c__DisplayClass10_0.<Map>b__2(JiraRevision r) at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
> at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
> at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) at JiraExport.JiraMapper.Map(JiraItem issue) at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical): at System.String.Substring(Int32 startIndex, Int32 length) at JiraExport.JiraMapper.MapEpicChildLink(JiraRevision r, List`1 links, String field, String type)
> at JiraExport.JiraMapper.MapLinks(JiraRevision r)
> at JiraExport.JiraMapper.MapRevision(JiraRevision r)
> at JiraExport.JiraMapper.<>c__DisplayClass10_0.b__2(JiraRevision r)
> at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext() at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
> at JiraExport.JiraMapper.Map(JiraItem issue)
> at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
> 
> The code line that's causing the problem is line 228:
> 
> ` var childKeyStr = value?.ToString().Substring(r.OriginId.LastIndexOf("-", StringComparison.InvariantCultureIgnoreCase) + 1);`
> 
> which is referencing the string length of the origin string. Changing the code to
> 
> ` var childKeyStr = value?.ToString().Substring((value?.ToString()).LastIndexOf("-", StringComparison.InvariantCultureIgnoreCase) + 1);`
> allows the export to complete.

i am getting the same error and in which file should i change that line i am not getting

**Comment by Harshithagp** [comment]
> JiraMapper.cs.

thank you

**Comment by Harshithagp** [comment]
same error even after replacing

**Comment by tung-nt-niteco** [comment]
@MattCodd2 do r.OriginId and value?.ToString() have the same value?
