### ISSUE TITLE
Getting this error message with import

### ISSUE THREAD

**Issue by hoodwink** [solidify/jira-azuredevops-migrator#283]
Final result of import  to TFS 2017 on prem says some thing like this:
[I][23:53:52] Import complete. Imported 2027 items, 20024 revisions (145 errors, 2053 warnings) in 01:06:11.

But got several of these same error messages while importing. Not sure if all the backlog items got imported, but here is the error message. I used config-scrum.json.
![image](https://user-images.githubusercontent.com/4923700/94354027-0fa2c100-0045-11eb-8b89-f07a66fb87df.png)

  [E][23:53:51] Failed to update fields.
[Microsoft.TeamFoundation.WorkItemTracking.Client.FieldDefinitionNotExistException] Microsoft.TeamFoundation.WorkItemTracking.Client.FieldDefinitionNotExistException: TF26027: A field definition Microsoft.VSTS.Common.ClosedBy in the work item type definition file does not exist. Add a definition for this field or remove the reference to the field and try again.
   at Microsoft.TeamFoundation.WorkItemTracking.Client.FieldDefinitionCollection.get_Item(String name)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.FieldCollection.get_Item(String name)
   at WorkItemImport.Agent.SetFieldValue(WorkItem wi, String fieldRef, Object fieldValue)
   at WorkItemImport.Agent.UpdateWIFields(IEnumerable`1 fields, WorkItem wi):
   at Microsoft.TeamFoundation.WorkItemTracking.Client.FieldDefinitionCollection.get_Item(String name)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.FieldCollection.get_Item(String name)
   at WorkItemImport.Agent.SetFieldValue(WorkItem wi, String fieldRef, Object fieldValue)
   at WorkItemImport.Agent.UpdateWIFields(IEnumerable`1 fields, WorkItem wi)
[W][23:53:51] ''ATL-2016', rev 4' - not all changes were saved.

**Comment by MOlausson** [comment]
@hoodwink we decided to treat this as an error since it cause data loss because the field in question does not have a definition for the target field for the specific work item type. The backlog item should be migrated but the missing fields will not.
