### ISSUE TITLE
The request was rejected by the server because of unicode control characters

### ISSUE THREAD

**Issue by Jeroenskie** [solidify/jira-azuredevops-migrator#29]
When there is an unicode control character (like \u000b) in the JSON file in the "Value":  section the JSON file import generates an error:

`[l:E][d:16:40:23] [Microsoft.TeamFoundation.TeamFoundationServerInvalidRequestException] The request was rejected by the server.
Technical information:
  HTTP code 400: Bad Request: 
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.ReadResponse(HttpWebResponse webResponse, WebException webException) 
at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.IsAuthenticationChallenge(TfsMessage requestMessage, HttpWebResponse webResponse, WebException webException, TfsMessage& responseMessage)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.SendRequest()
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpRequestChannel.Request(TfsMessage message, TimeSpan timeout)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpClientBase.Invoke(TfsClientOperation operation, Object[] parameters, TimeSpan timeout, Object[]& outputs)
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.ClientService.Update(XmlNode package, XmlNode& result, MetadataTableHaveEntry[] metadataHave, String& dbStamp, RowSetCollection& metadata)
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.WorkItemServer.Update(String requestId, XmlElement package, XmlElement& result, MetadataTableHaveEntry[] metadataHave, String& dbStamp, IMetadataRowSets& metadata)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SendUpdatePackage(XmlElement package, XmlElement& result, Boolean bulk)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SaveWorkItems(WorkItem[] workitems, Boolean bulk, SaveFlags saveFlags)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.Save(SaveFlags saveFlags)
   at WorkItemImport.Agent.SaveWorkItem(WiRevision rev, WorkItem newWorkItem) in C:\jira-azuredevops-migrator\WorkItemImport\Agent.cs:line 645
   at WorkItemImport.Agent.ImportRevision(WiRevision rev, WorkItem wi) in C:\jira-azuredevops-migrator\WorkItemImport\Agent.cs:line 763`

Wen we looked into the issue we can see at this situation it's a copy/paste action from a Confluence table in the description field. 

Is it possible to validate on this and escape or delete these unicode control characters in the export step?

**Comment by MOlausson** [comment]
Hi @Jeroenskie, it sounds like something we should handle. Would it be possible for you to post a sample here?

**Comment by Jeroenskie** [comment]
Hi @MOlausson, thanks for looking into it. Below an example, if you need more info please let me know.
![dat-263](https://user-images.githubusercontent.com/13356814/54022899-d8836b00-4193-11e9-83ef-3963a919d690.png)

**Comment by MOlausson** [comment]
Perfect @Jeroenskie, good description and should help us repro the issue.

**Comment by MOlausson** [comment]
Hi @Jeroenskie , I finally got to look at this. I cannot reproduce, can you help me how I can setup a test for this? We'll add some form of scrubbing to the text to avoid the problem but I would like to have a test case for it.

**Comment by amitnavehjob** [comment]
+1 
Happened to me as well and for me the whole first revision's info wasn't written because of that.

I've attached the import log and the JIRA issue json.

[server_rejected_unicode.zip](https://github.com/solidify/jira-azuredevops-migrator/files/3551373/server_rejected_unicode.zip)

**Comment by AmitNaveh23** [comment]
+1 
It happened to me also and because of that the whole first revision (had Unicode characters in one of the fields) wasn't written.

I've attached the import log + Jira issue json 

[server_rejected_unicode.zip](https://github.com/solidify/jira-azuredevops-migrator/files/3551412/server_rejected_unicode.zip)
