### ISSUE TITLE
Jira Export Query throwing errors when selecting multiple options

### ISSUE THREAD

**Issue by charankumarneela** [solidify/jira-azuredevops-migrator#294]
**Describe the bug**

We are migrating from Jira to Azure Devops using solidify Tools and during the export of Jira Data, it is exporting all the DONE and Not Required Work Items  even though we have selected the filter

"query": "project = Test AND issuetype IN project in (XX, "Property API", "XX") AND issuetype in (Bug, Spike, Story, task, Sub-Bug, Sub-task) AND status in ("Initial Idea", "Bugs to be triaged", "Product Backlog", Doing, "To Do", Planning, "Ready for Review", "In Test", "Test Review", "Done") AND (fixVersion in unreleasedVersions() OR fixVersion is EMPTY) ORDER BY status DESC, fixVersion ASC",

please advise if the above query string is not support or any fields are missing, as the same query works in JIRA 
 
 
[config.txt](https://github.com/solidify/jira-azuredevops-migrator/files/5464584/config.txt)

**Comment by charankumarneela** [comment]
[E][11:41:10] Cannot deserialize the JSON text from configuration file. Please ensure it is formatted properly.
[E][11:41:10] Unexpected migration error.
[Newtonsoft.Json.JsonReaderException] Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: I. Path 'query', line 4, position 109.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Migration.Common.Config.ConfigReaderJson.DeserializeText(String input)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical):
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Migration.Common.Config.ConfigReaderJson.DeserializeText(String input)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
