### ISSUE TITLE
Error Retrieving jira fields (default backend - 404) with jira on server

### ISSUE THREAD

**Issue by Jonheidur** [solidify/jira-azuredevops-migrator#343]
Hi,

My jira system is on server and hosted by a third party so this might be due to access issue, but I had some issue with "Connecting to Jira" that were resolved when using email and accessToken. I did not include /jira in the url since when I did that I got a 401 error on "Retrieving Jira fields..." step.

I ran the following and got the error below.
C:\jira-azuredevops-migrator-2.3.117>jira-export -u xxx@xxx.com -p AccessToken --url https://xxx.xxx.com --config config-scrum.json --force

 I have admin rights on the jira system. Can you tell me what the below error means? and if it is connection related of is something else could be the issue. I have attched the error log.

Best, Jónheiður 
---

**Error:**
Jira Exporter v2.3.117
Copyright (c) Solidify
[I][13:49:06] Connecting to Jira...
[I][13:49:06] Retrieving Jira fields...
[E][13:49:06] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> Atlassian.Jira.Remote.ResourceNotFoundException: Response Content: default backend - 404
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Atlassian.Jira.Remote.IssueFieldService.<GetCustomFieldsAsync>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at JiraExport.JiraProvider.Initialize(JiraSettings settings)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
[jira-export-log-210311-140737.txt](https://github.com/solidify/jira-azuredevops-migrator/files/6123507/jira-export-log-210311-140737.txt)

AB#4673

**Comment by Jonheidur** [comment]
This was solved by adding /jira to the URL and using a username and password for a local admin user.
