### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by advitakhadke24** [solidify/jira-azuredevops-migrator#366]
Hi,
I was able to export multiple items using Solidify from our On-Prem Jira. For some items I am getting a System.NullReferenceException (attached below) For now I just skipped the tasks which were giving me this error but now I  would like to migrate the items that were throwing me the exception.

Exception: 
[I][15:49:46] Connecting to Jira...
[I][15:49:46] Retrieving Jira fields...
[I][15:49:46] Retrieving Jira link types...
[I][15:49:46] Export started. Exporting 1 items.
[W][15:49:46] User mapping file 'C:\Temp\JiraExport\inprogress\users.txt' not found, ignoring mapping user identities.
[I][15:49:46] Initializing Jira field mapping...
[I][15:49:46] Processing 1/1 - 'IDO-839'.
[E][15:49:46] Unexpected migration error.
[System.NullReferenceException] System.NullReferenceException: Object reference not set to an instance of an object.
   at JiraExport.JiraItem.<>c__DisplayClass2_0.<BuildCommentRevisions>b__0(Comment c, Int32 i)
   at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at JiraExport.JiraItem.BuildCommentRevisions(JiraItem jiraItem, JiraProvider jiraProvider)
   at JiraExport.JiraItem.BuildRevisions(JiraItem jiraItem, JiraProvider jiraProvider)
   at JiraExport.JiraItem.CreateFromRest(String issueKey, JiraProvider jiraProvider)
   at JiraExport.JiraProvider.<EnumerateIssues>d__23.MoveNext()
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical):
   at JiraExport.JiraItem.<>c__DisplayClass2_0.<BuildCommentRevisions>b__0(Comment c, Int32 i)
   at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at JiraExport.JiraItem.BuildCommentRevisions(JiraItem jiraItem, JiraProvider jiraProvider)
   at JiraExport.JiraItem.BuildRevisions(JiraItem jiraItem, JiraProvider jiraProvider)
   at JiraExport.JiraItem.CreateFromRest(String issueKey, JiraProvider jiraProvider)
   at JiraExport.JiraProvider.<EnumerateIssues>d__23.MoveNext()
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)

Any help on whether I'm doing something wrong would be appreciated.

Best regards,
Advita

AB#5088

**Comment by lula-code** [comment]
Hi,
check: https://github.com/solidify/jira-azuredevops-migrator/issues/328

If it is only one ticket: Check that a user is set everywhere on the ticket (reporter, assignee, etc.).

**Comment by advitakhadke24** [comment]
Hi,

It's not just one ticket instead there are multiple, I did check the user, the user is set everywhere on the ticket.

**Comment by advitakhadke24** [comment]
@lula-code Just wondering if you have any inputs on my previous  post, Thanks!

**Comment by madkoo** [comment]
@advitakhadke24  based on the provided info i would guess that on the tasks its trying to get comments but it fails to retrieve rendered fields. 
If you make a query "https://ADD_YOUR_URL/rest/api/2/issue/'IDO-839?expand=renderedFields" and if you search under rendered filled for comments then are there any comments ?

**Comment by advitakhadke24** [comment]
@lula-code @madkoo Thanks for getting back,  I think I found out the issue, All the tasks that were throwing exceptions seems like for all those tasks there is 1 common thing all those tasks have anonymous users in comments which  I guess Solidify could not identity and that's why it is throwing error. 
Is there a solution to get pass this issue? 
Thank you!

**Comment by lula-code** [comment]
Hi,
As I have already written: Check: https://github.com/solidify/jira-azuredevops-migrator/issues/328
The user had the same problem and was able to solve it. 
This solution is not complex, but it solves the problem.

Your steps:
1. Download the source code.
2. Open the code in Visual Studio
3. Add the following changes: https://github.com/hochstetter/jira-azuredevops-migrator/commit/0214fc461791a01e6ce055a7d1f516b617ee5ada
4. Build this solution
5. Be happy :)

**Comment by advitakhadke24** [comment]
Thanks @lula-code @madkoo Closing the issue
