### ISSUE TITLE
Unable to import data into ADO

### ISSUE THREAD

**Issue by harishtc** [solidify/jira-azuredevops-migrator#410]
Hi Team,

I am trying to import data from Jira to ADO though solidify (version : 2.3.117). export has been done smooth. but, while coming to import, i am facing challenges.
i've shared you the log file data below, could you please check and help me on this.

-------------------------------------------------------------------------------------------
[I][12:54:48] Connecting to Azure DevOps/TFS...
[E][12:54:49] Unexpected migration error.
[Microsoft.TeamFoundation.TeamFoundationServerInvalidResponseException] Microsoft.TeamFoundation.TeamFoundationServerInvalidResponseException: 
Please contact your administrator. There was an error contacting the server.
Technical information (for administrator):
  HTTP code 200: OK
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.ReadMessage(HttpWebResponse webResponse, WebException webException, Stream responseStream, Boolean& closeResponse)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.ReadResponse(HttpWebResponse webResponse, WebException webException)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.IsAuthenticationChallenge(TfsMessage requestMessage, HttpWebResponse webResponse, WebException webException, TfsMessage& responseMessage)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.SendRequest()
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpRequestChannel.Request(TfsMessage message, TimeSpan timeout)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpClientBase.Invoke(TfsClientOperation operation, Object[] parameters, TimeSpan timeout, Object[]& outputs)
   at Microsoft.TeamFoundation.Framework.Client.LocationWebService.Connect(Int32 connectOptions, Int32 lastChangeId, Int32 features)
   at Microsoft.TeamFoundation.Framework.Client.FrameworkServerDataProvider.Connect(ConnectOptions connectOptions)
   at Microsoft.TeamFoundation.Client.TfsConnection.EnsureProviderConnected()
   at WorkItemImport.Agent.EstablishSoapConnection(Settings settings)
   at WorkItemImport.Agent.Initialize(MigrationContext context, Settings settings)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical): 
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.ReadMessage(HttpWebResponse webResponse, WebException webException, Stream responseStream, Boolean& closeResponse)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.ReadResponse(HttpWebResponse webResponse, WebException webException)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.IsAuthenticationChallenge(TfsMessage requestMessage, HttpWebResponse webResponse, WebException webException, TfsMessage& responseMessage)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.SendRequest()
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpRequestChannel.Request(TfsMessage message, TimeSpan timeout)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpClientBase.Invoke(TfsClientOperation operation, Object[] parameters, TimeSpan timeout, Object[]& outputs)
   at Microsoft.TeamFoundation.Framework.Client.LocationWebService.Connect(Int32 connectOptions, Int32 lastChangeId, Int32 features)
   at Microsoft.TeamFoundation.Framework.Client.FrameworkServerDataProvider.Connect(ConnectOptions connectOptions)
   at Microsoft.TeamFoundation.Client.TfsConnection.EnsureProviderConnected()
   at WorkItemImport.Agent.EstablishSoapConnection(Settings settings)
   at WorkItemImport.Agent.Initialize(MigrationContext context, Settings settings)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
[I][12:54:49] Import complete. Imported 0 items, 0 revisions (1 errors, 0 warnings) in 00:00:01.

Regards,
Harish.

AB#5995

**Comment by harishtc** [comment]
guess there is a problem with access token i am using in cmd promt . but exactly not sure.

**Comment by Alexander-Hjelm** [comment]
We cannot support you with authentication errors, as there is nothing wrong with the tool itself. Make sure you are using a valid Azure Devops PAT for you organization, and that the PAT is entered correctly in the config file.

**Comment by harishtc** [comment]
Hi Alexander,

May i know the mapper we can use to copy the reporter value from Jira to ADO. could you please let me know on this ?.

Regards,
Harish.

**Comment by Alexander-Hjelm** [comment]
It should be MapUser, as of https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/config.md

**Comment by harishtc** [comment]
Hi Team,

I could see similar type of error "Cannot add 'Child' CEN-164 link to 'Parent' CEN-165, 'Child' link-map configuration missing." many times during the import. can you help me how can i resolve this.

Regards,
Harish.

**Comment by harishtc** [comment]
Team, any update on this ?.

**Comment by Alexander-Hjelm** [comment]
With regards to the Effort field missing, this field is specific to PBIs in the Scrum process template. It might be that you are migrating to a different proccess or work item type. Refer to: 
https://docs.microsoft.com/en-us/azure/devops/reference/xml/reportable-fields-reference?view=azure-devops-2020#measure

As for the child links not being added. Maybe you are trying to create a child-parent relationship between two workitem types where this is not allowed. Try to create the link manually in AzDO and see if it succeeds. Otherwise maybe refer to this issue: https://github.com/solidify/jira-azuredevops-migrator/issues/163

**Comment by Alexander-Hjelm** [comment]
Closing support ticket due to inactivity. Feel free to open the issue again if the issue persists :)
