### ISSUE TITLE
unable to import to Azure Boards

### ISSUE THREAD

**Issue by Tejanarni** [solidify/jira-azuredevops-migrator#449]
Hello Everyone.

I am unable to import to Azure Boards>

Here are the logs & kindly please help . Thank you

Work Item Importer v2.3.117
Copyright (c) Solidify
[W][14:38:39] User mapping file 'C:\Temp\JiraExport\users.txt' not found, ignoring mapping user identities.
[I][14:38:39] Connecting to Azure DevOps/TFS...
[I][14:38:41] Retreiving project info from Azure DevOps/TFS...
[I][14:38:42] Building iteration cache...
[I][14:38:42] Building area cache...
[I][14:38:42] Building execution plan...
[I][14:38:42] Import started. Importing 2 items with 6 revisions.
[E][14:38:43] Failed to import 'TES-1/-1, 0'.
[Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeDeniedOrNotExistException] Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeDeniedOrNotExistException: TF201077: The work item type Product Backlog Item cannot be found. It may have been renamed or destroyed.
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeCollection.get_Item(String typeName)
   at WorkItemImport.Agent.CreateWI(String type)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical):
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeCollection.get_Item(String typeName)
   at WorkItemImport.Agent.CreateWI(String type)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
[E][14:38:43] Failed to import 'TES-1/-1, 1'.
[Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeDeniedOrNotExistException] Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeDeniedOrNotExistException: TF201077: The work item type Product Backlog Item cannot be found. It may have been renamed or destroyed.
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeCollection.get_Item(String typeName)
   at WorkItemImport.Agent.CreateWI(String type)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical):
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeCollection.get_Item(String typeName)
   at WorkItemImport.Agent.CreateWI(String type)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
[E][14:38:43] Failed to import 'TES-1/-1, 2'.
[Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeDeniedOrNotExistException] Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeDeniedOrNotExistException: TF201077: The work item type Product Backlog Item cannot be found. It may have been renamed or destroyed.
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeCollection.get_Item(String typeName)
   at WorkItemImport.Agent.CreateWI(String type)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical):
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeCollection.get_Item(String typeName)
   at WorkItemImport.Agent.CreateWI(String type)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
[E][14:38:43] Failed to import 'TES-1/-1, 3'.
[Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeDeniedOrNotExistException] Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeDeniedOrNotExistException: TF201077: The work item type Product Backlog Item cannot be found. It may have been renamed or destroyed.
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeCollection.get_Item(String typeName)
   at WorkItemImport.Agent.CreateWI(String type)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical):
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeCollection.get_Item(String typeName)
   at WorkItemImport.Agent.CreateWI(String type)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
[E][14:38:43] Failed to import 'TES-1/-1, 4'.
[Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeDeniedOrNotExistException] Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeDeniedOrNotExistException: TF201077: The work item type Product Backlog Item cannot be found. It may have been renamed or destroyed.
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeCollection.get_Item(String typeName)
   at WorkItemImport.Agent.CreateWI(String type)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical):
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeCollection.get_Item(String typeName)
   at WorkItemImport.Agent.CreateWI(String type)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
[I][14:38:43] Processing 1/6 - wi 'Initial revision', jira 'TES-2, rev 0'.
[I][14:38:43] Import complete. Imported 2 items, 6 revisions (5 errors, 1 warnings) in 00:00:04.****

**Comment by Alexander-Hjelm** [comment]
The Work Item type "Product Backlog Item" does not exist on your target Azure DevOps oragnization :)
