### ISSUE TITLE
Problem with the attachments

### ISSUE THREAD

**Issue by yfrindel** [solidify/jira-azuredevops-migrator#50]
Hi, all seems fine except with the attachements. I have the following message with a ticket (during the JIRA import step) : 

```
[E][18:34:42] Cannot find info for attachment '12604'. Skipping.
[System.InvalidOperationException] System.InvalidOperationException: Response Status Code: 404. Response Content: {"errorMessages":["La pièce jointe avec l'ID '12604' n'existe pas"],"errors":{}}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at JiraExport.JiraProvider.<GetAttachmentInfo>d__18.MoveNext():
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at JiraExport.JiraProvider.<GetAttachmentInfo>d__18.MoveNext()
[E][18:34:42] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at JiraExport.JiraProvider.<DownloadAttachmentAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at JiraExport.JiraProvider.<DownloadAttachments>d__27.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at JiraExport.JiraMapper.MapAttachments(JiraRevision rev)
   at JiraExport.JiraMapper.MapRevision(JiraRevision r)
   at JiraExport.JiraMapper.<>c__DisplayClass8_0.<Map>b__2(JiraRevision r)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at JiraExport.JiraMapper.Map(JiraItem issue)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at JiraExport.JiraProvider.<DownloadAttachmentAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at JiraExport.JiraProvider.<DownloadAttachments>d__27.MoveNext()<---
:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at JiraExport.JiraMapper.MapAttachments(JiraRevision rev)
   at JiraExport.JiraMapper.MapRevision(JiraRevision r)
   at JiraExport.JiraMapper.<>c__DisplayClass8_0.<Map>b__2(JiraRevision r)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at JiraExport.JiraMapper.Map(JiraItem issue)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh)
```

All the process is stopped, so the import is not correctly finished.
Does someone could help me please ? thx

**Comment by Jura** [comment]
I have the same issue - image in comment is referenced but missing on server, it would be useful to have an option to skip over attachment errors to continue export.

**Comment by yfrindel** [comment]
I added a "Try Catch" in the class JiraMapper.cs to fix the problem :

![Uploading Capture.GIF…]()

**Comment by MOlausson** [comment]
Thanks for the feedback @yfrindel and @Jura. What about an option like "ignore-failed-links": true for choosing to treat missing linked work items as workings or error? For instance ignore-failed-attachments where true => warnings and false => errors?

**Comment by Jura** [comment]
Sounds good to me, warnings instead of aborts are exactly what I'm looking for. Thanks

**Comment by yfrindel** [comment]
Sounds good to me too. Thx

**Comment by yfrindel** [comment]
May I ask why 7 for "download-options" please ?

**Comment by yfrindel** [comment]
Sometimes, in a ticket, an attachment is created, then deleted or renamed. So, in my opinion, that's why the program doesn't find the attachment, and that's certainly why I have this kind of error : 

```
Cannot find info for attachment '12785'. Skipping.
[System.InvalidOperationException] System.InvalidOperationException: Response Status Code: 404. Response Content: {"errorMessages":["La pièce jointe avec l'ID '12785' n'existe pas"],"errors":{}}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at JiraExport.JiraProvider.<GetAttachmentInfo>d__18.MoveNext() in C:\Source\NOTOCORD-JIRAmigrationGIT\src\WorkItemMigrator\JiraExport\JiraProvider.cs:line 82:
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at JiraExport.JiraProvider.<GetAttachmentInfo>d__18.MoveNext() in C:\Source\NOTOCORD-JIRAmigrationGIT\src\WorkItemMigrator\JiraExport\JiraProvider.cs:line 82
[E][09:55:12] Application stopped due to an error with the attachments
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at JiraExport.JiraProvider.<DownloadAttachmentAsync>d__19.MoveNext() in C:\Source\NOTOCORD-JIRAmigrationGIT\src\WorkItemMigrator\JiraExport\JiraProvider.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at JiraExport.JiraProvider.<DownloadAttachments>d__27.MoveNext() in C:\Source\NOTOCORD-JIRAmigrationGIT\src\WorkItemMigrator\JiraExport\JiraProvider.cs:line 266
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at JiraExport.JiraMapper.MapAttachments(JiraRevision rev) in C:\Source\NOTOCORD-JIRAmigrationGIT\src\WorkItemMigrator\JiraExport\JiraMapper.cs:line 204
   at JiraExport.JiraMapper.MapRevision(JiraRevision r) in C:\Source\NOTOCORD-JIRAmigrationGIT\src\WorkItemMigrator\JiraExport\JiraMapper.cs:line 102
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at JiraExport.JiraProvider.<DownloadAttachmentAsync>d__19.MoveNext() in C:\Source\NOTOCORD-JIRAmigrationGIT\src\WorkItemMigrator\JiraExport\JiraProvider.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at JiraExport.JiraProvider.<DownloadAttachments>d__27.MoveNext() in C:\Source\NOTOCORD-JIRAmigrationGIT\src\WorkItemMigrator\JiraExport\JiraProvider.cs:line 266<---
:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at JiraExport.JiraMapper.MapAttachments(JiraRevision rev) in C:\Source\NOTOCORD-JIRAmigrationGIT\src\WorkItemMigrator\JiraExport\JiraMapper.cs:line 204
   at JiraExport.JiraMapper.MapRevision(JiraRevision r) in C:\Source\NOTOCORD-JIRAmigrationGIT\src\WorkItemMigrator\JiraExport\JiraMapper.cs:line 102
```
(I tried with the last source code of the program)
Maybe just creating (or adding the revision) without the attachment could be enough in this case ?

**Comment by MOlausson** [comment]
> May I ask why 7 for "download-options" please ?

It's a bit field so all options => 1 + 2 +4 ? 7. I should clarify this in the docs.

**Comment by dan-miller** [comment]
@MOlausson is this issue still being worked?

**Comment by MOlausson** [comment]
I've created a release for this now, it was actually a bug as I see it. I cannot repro with the test data I have at hands so great if someone can test v2.2.24.

**Comment by MOlausson** [comment]
> @MOlausson is this issue still being worked?

Check out release v2.2.24.

**Comment by yfrindel** [comment]
I will try to check the new version ASAP

**Comment by yfrindel** [comment]
Just to understand, could you tell me, please, if the workitem is created (or not) when an attachment is not found ?

**Comment by dan-miller** [comment]
> > @MOlausson is this issue still being worked?
> 
> @dan-miller, Check out release v2.2.24.

We've moved past the attachment error, but now I can't seem to find the output directory/files
![image](https://user-images.githubusercontent.com/3630374/57852608-925d1000-77b1-11e9-86f3-97863a603424.png)

**Comment by yfrindel** [comment]
The process of migration is very very very long...Is it possible to reduce the timeout value when an exception is thrown ? (for example when an attachment is not found)

![image](https://user-images.githubusercontent.com/22955005/57868709-ca8d3e80-7803-11e9-80e3-0d873d646dfb.png)

![image](https://user-images.githubusercontent.com/22955005/57868792-f1e40b80-7803-11e9-9ab2-bf2d8eb9a594.png)

**Comment by MOlausson** [comment]
> Just to understand, could you tell me, please, if the workitem is created (or not) when an attachment is not found ?
> And, Do you know why I have this message "User 'admin' not found in Jira, using username 'admin' for mapping" ?

@yfrindel yes the work item is created regardless but attachments may be missing. Regarding the user warning it comes from not finding the user in Jira. Is there a user called Admin still? I don't know that code so well, we might check agains email adresses so will have to check.

**Comment by MOlausson** [comment]
@yfrindel regarding perf I don't see the exceptions taking time, from your screenshots it looks like the api calls in general takes a long time in your case. Are you accessing the Jira server remote over network with latency? I also just pushed an update where I changed the above exception to a warning to be inline with how other non-critical situations are handled.

**Comment by MOlausson** [comment]
Closing this as it should work as design now. @yfrindel let me know if you find something that's not as expected.

**Comment by yfrindel** [comment]
Hi. and thanks for your answer.

"Are you accessing the Jira server remote over network with latency?" => yes it's possible. I will try directly from 1 of our boxes.

**Comment by yfrindel** [comment]
I have still a problem with the type "Test". When I try to import a "Test" from Jira, the workitem is empty if it's mapped with the type "Test Case" of VSTS. Could you help me please ?
