### ISSUE TITLE
Receiving an error when I try to run jira-exporter

### ISSUE THREAD

**Issue by Alexander-Hjelm** [solidify/jira-azuredevops-migrator#517]
(Originally emailed to the JIRA support box by spm6711@psu.edu)

Hello,

I am trying to migrate from Jira to Azure Devop’s.   We are running a type: Kanban in Jira, and I would like to try to migrate to a Agile framework in Azure Devop’s.   Every time I run, I am receiving the following error message, and after looking through the documentation, and debugging the code, I am unable to figure out what exactly is causing the issue.  For the most part I was running the config-agile, with just the source-project, target-project, and the query updated for the project under the jira directory I am using.   I’ve run the config-agile through parser’s and validator’s so there are no malformed data structures in it.   I am not quite sure what else to try at this point.   Hopefully you have seen the issue and know how to resolve it.    I haven’t seen any specific directions on how to export ‘Kanban’ type’s, but from my understanding it’s mainly an agile board, with custom table elements.  I am probably wrong about that though.   Any assistance would be appreciated. Thank you.

Versions I’ve tried: Latest master branch, and Release 2.3.117 (both run into the same error)

Failure always occurs just after the breakpoint in the JiraProvider.cs file (line 49) of Master Branch:

![image](https://user-images.githubusercontent.com/10683896/184615319-172981ca-3295-4c48-b799-18112cf740c7.png)

It will pop out to JiraCommandLine.cs general exception Line 141
 
Stack Error:

```
[I][16:45:25] Connecting to Jira...
[I][16:45:25] Retrieving Jira fields...
[E][16:45:26] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'Atlassian.Jira.Remote.RemoteField[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path '', line 1, position 2.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternaleader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Atlassian.Jira.Remote.IssueFieldService.<GetCustomFieldsAsync>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at JiraExport.JiraProvider.Initialize(JiraSettings settings)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
---> (Inner Exception #0) Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'Atlassian.Jira.Remote.RemoteField[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
```

**Comment by Alexander-Hjelm** [comment]
Sounds very strange. This behavior doesn't usually happen, so most likely it's related to your JIRA instance.

Judging by the error message, it seems that the list of fields from the JIRA API is not JSON-parsable, which sounds very strange...

A few suggestions:
- Try and see if you can intercept the HTTP response inside GetCustomFieldsAsync(), or maybe that class is from the JIRA api library? Then you won't be able to open it...
- Try to make a manual rest call to get all the fields of your JIRA instance, and see what you get. Set up a REST API call in Postman or some similar tool. See: https://docs.atlassian.com/software/jira/docs/api/REST/1000.824.0/#api/2/field-getFields
