### ISSUE TITLE
Unable to connect to JIRA - SSL/TLS channel

### ISSUE THREAD

**Issue by himemelody** [solidify/jira-azuredevops-migrator#558]
This [here](https://community.atlassian.com/t5/Jira-questions/Getting-error-The-request-was-aborted-Could-not-create-SSL-TLS/qaq-p/1127305) seems to suggest the Security Protocol needs to be set to `Tls12`? Not seen a way to set this from the exe. Has this come up before? 

Error
`Could not create SSL/TLS secure channel.`

Version
jira-azuredevops-migrator-2.3.117

Command: 
```
jira-export -u XXXX -p XXXX --url https://XXX.atlassian.net --config config-scrum.json --force
```

Trace
```
Jira Exporter v2.3.117
Copyright (c) Solidify
[I][15:46:07] Connecting to Jira...
[I][15:46:07] Retrieving Jira fields...
[E][15:47:10] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurr
ed. ---> System.InvalidOperationException: Error Message: The request was aborte
d: Could not create SSL/TLS secure channel.
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest
 request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10`1.MoveNext
()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Atlassian.Jira.Remote.IssueFieldService.<GetCustomFieldsAsync>d__2.MoveNex
t()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at JiraExport.JiraProvider.Initialize(JiraSettings settings)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOpt
ion password, CommandOption url, CommandOption configFile, Boolean forceFresh, C
ommandOption continueOnCritical)
---> (Inner Exception #0) System.InvalidOperationException: Error Message: The r
equest was aborted: Could not create SSL/TLS secure channel.
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest
 request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10`1.MoveNext
()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Atlassian.Jira.Remote.IssueFieldService.<GetCustomFieldsAsync>d__2.MoveNex
t()<---
:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at JiraExport.JiraProvider.Initialize(JiraSettings settings)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOpt
ion password, CommandOption url, CommandOption configFile, Boolean forceFresh, C
ommandOption continueOnCritical)
[I][15:47:10] Export complete. Exported 0 items (1 errors, 0 warnings) in 00:01:
03.

```

**Comment by Alexander-Hjelm** [comment]
This isn't really out domain unfortunately. One of the prerequisites of using the jira-ADO migrator is having a stable connection to the source JIRA instance, and we cannot help you troubleshoot your network issues :)

**Comment by himemelody** [comment]
This is for connecting to JIRA Cloud, not my own server. 

This I think is the line where the optional parameter can be given to set the SecurityProtocol.

https://github.com/solidify/jira-azuredevops-migrator/blob/master/src/WorkItemMigrator/JiraExport/JiraServiceWrapper.cs#L28

**Comment by Alexander-Hjelm** [comment]
In that case I think it would be best if you checked with the team behind the Atlassian.Jira library :)
