### ISSUE TITLE
Basic authentication is no longer support

### ISSUE THREAD

**Issue by Naytron** [solidify/jira-azuredevops-migrator#579]
**Describe the problem**
I am not able to connect to Jira with the example provided

The message says that basic authentication is no longer supported

**To Reproduce**
1. open command prompt
2. navigate to tool location - jira-export.exe
3. Run command as is in the documentation
jira-export -u myemail@email.com -p Password --url https://myproject.atlassian.net/ --config config-scrum.json --force
4. You get this error [attachment included]
Jira Exporter v2.3.117
Copyright (c) Solidify
[I][09:08:01] Connecting to Jira...
[I][09:08:01] Retrieving Jira fields...
[E][09:08:02] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.Security.Authentication.AuthenticationException: Response Content: Basic authentication with passwords is deprecated.  For more information, see: https://developer.atlassian.com/cloud/confluence/deprecation-notice-basic-auth/
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Atlassian.Jira.Remote.IssueFieldService.<GetCustomFieldsAsync>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at JiraExport.JiraProvider.Initialize(JiraSettings settings)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)

**Tool version**
 jira-azuredevops-migrator tool  2.3.117

**Screenshots**

<img width="1678" alt="jira-basic-auth-not-supported" src="https://user-images.githubusercontent.com/1117015/196473487-57732406-9638-4e02-8a43-0d2a26fc88fa.png">

**Comment by Naytron** [comment]
do in place of the password put the token or is there another command arg?

[wow thanks for the fast response also]

**Comment by Alexander-Hjelm** [comment]
As the password arg :)

**Comment by Naytron** [comment]
thanks so much!!!
