### ISSUE TITLE
Project Name does not exist

### ISSUE THREAD

**Issue by kelos-01** [solidify/jira-azuredevops-migrator#664]
Not sure what I'm doing wrong here. I've tried multiple variations of the project name using the full name or project code, even directly coping the JQL `project = "MP2" ORDER BY Rank ASC' from JIRA but still get this error.

`"The value 'MP2' does not exist for the field 'project'."`

Jira Exporter v3.0.54
Copyright (c) Solidify
[I][10:15:30] Connecting to Jira...
[I][10:15:30] Retrieving Jira fields...
[I][10:15:32] Retrieving Jira link types...
[D][10:15:33]    Get item count using query: 'project=MP2 ORDER BY Rank ASC'
[E][10:15:33] Failed to get item count using query: 'project=MP2 ORDER BY Rank ASC'
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'MP2' does not exist for the field 'project'.","Not able to sort using field 'Rank'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
---> (Inner Exception #0) System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'MP2' does not exist for the field 'project'.","Not able to sort using field 'Rank'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()<---
:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
[I][10:15:34] Export started. Exporting 0 items.
[W][10:15:35] Epic link field missing for config field 'Epic Link'.
[W][10:15:35] Sprint link field missing for config field 'Sprint'.
[W][10:15:35] User mapping file 'C:\Temp\JiraExport\users.txt' not found, ignoring mapping user identities.
[I][10:15:35] Initializing Jira field mapping...
[W][10:15:35] No target type 'Feature' is set, field status cannot be mapped.
[W][10:15:35] No target type 'User Story' is set, field status cannot be mapped.
[D][10:15:35]    Enumerate remote issues
[E][10:15:35] Failed to retrieve issues
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'MP2' does not exist for the field 'project'.","Not able to sort using field 'Rank'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.<EnumerateIssues>d__26.MoveNext()
---> (Inner Exception #0) System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'MP2' does not exist for the field 'project'.","Not able to sort using field 'Rank'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()<---
:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.<EnumerateIssues>d__26.MoveNext()
[I][10:15:35] Export complete. Exported 0 items (2 errors, 5 warnings) in 00:00:05.

If you receive a 400 error after the "Retrieving Jira link types" process starts you need to use your email address as your username -u EMAIL_ADDRESS [Link] (https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/overview.md) - Tired this as well; still the same error.

Command being run in cmd is:
jira-export -u user.name@domain.com -p API_TOKENHERE --url https://group.atlassian.net/ --config config-agile.json --force

Not sure what else to try.

**Comment by Alexander-Hjelm** [comment]
Read through the docs carefully :)

The jira project name needs to be specified in both the `source-project` field and the query:

```json
"source-project": "ProjectName",
"query": "project=ProjectName ORDER BY Rank ASC"
```

**Comment by kelos-01** [comment]
Nah I'm still getting the same error. I've tried changing them to match but still no luck. Even the Key field. Not sure what else I could try?

PS. thank you for your help

**Comment by Alexander-Hjelm** [comment]
This has worked for me before:

```json
{
    "source-project": "Agile-Demo",
    "query": "project = \"AGILEDEMO\" ORDER BY created DESC",
```

Where `Agile-Demo` is the jira project name and `AGILEDEMO` is the project key
