### ISSUE TITLE
[System.ArgumentNullException] System.ArgumentNullException: Value cannot be null. Parameter name: key

### ISSUE THREAD

**Issue by pdonat01** [solidify/jira-azuredevops-migrator#688]
Hi,
could you help where can i start to find the following error:

[I][12:35:03] Connecting to Jira...
[I][12:35:03] Retrieving Jira fields...
[I][12:35:04] Retrieving Jira link types...
[D][12:35:05]    Get item count using query: 'project=SONDEV ORDER BY Rank ASC'
[I][12:35:06] Export started. Exporting 11248 items.
[W][12:35:07] Epic link field missing for config field 'customfield_10002'.
[W][12:35:07] Sprint link field missing for config field 'customfield_10001'.
[W][12:35:07] User mapping file 'C:\Temp\JiraExport\' not found, ignoring mapping user identities.
[I][12:35:07] Initializing Jira field mapping...
[W][12:35:07] No target type 'Feature' is set, field status cannot be mapped.
[D][12:35:07]    Enumerate remote issues
[I][12:35:08] Processing 1/11248 - 'SONDEV-11105'.
[D][12:35:09]    Downloaded item.
[E][12:35:09] Unexpected migration error.
[System.ArgumentNullException] System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at JiraExport.JiraItem.ExtractFields(String key, JObject remoteIssue, IJiraProvider jira)
   at JiraExport.JiraItem.BuildRevisions(JiraItem jiraItem, IJiraProvider jiraProvider)
   at JiraExport.JiraItem.CreateFromRest(String issueKey, IJiraProvider jiraProvider)
   at JiraExport.JiraProvider.<EnumerateIssues>d__26.MoveNext()
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical):
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at JiraExport.JiraItem.ExtractFields(String key, JObject remoteIssue, IJiraProvider jira)
   at JiraExport.JiraItem.BuildRevisions(JiraItem jiraItem, IJiraProvider jiraProvider)
   at JiraExport.JiraItem.CreateFromRest(String issueKey, IJiraProvider jiraProvider)
   at JiraExport.JiraProvider.<EnumerateIssues>d__26.MoveNext()
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
[I][12:35:09] Export complete. Exported 11248 items (1 errors, 4 warnings) in 00:00:06.

**Comment by Alexander-Hjelm** [comment]
Hello @pdonat01 :)

Hard to say from just this information, but there is definitely a bug. A dictionary insert fails somewhere inside `JiraIterm.ExtractFields()`. It probably has something to do with misconfiguration at your end, but we should implement a more helpful log message.

Could you provide us with your config file and the full export log, for future reference?

We need additional information from the debugger to proceed. We can do this in one of two ways:

- You clone the source code and debug the tool locally in Visual Studio (e.g. community edition), and provide us with the information we need from the VS debugger.
- You provide us with a Jira API token over a private channel, and I can run some tests against your Jira organization to try and reproduce the error. You can revoke the token as soon as we are done.
  - If security is an issue, you can always set up a sandbox project in Jira with only a sample of the problematic issues and obfuscate sensitive data. As long as the issue is reproduceable.

Let me know which method would suit you best!

// Alexander

**Comment by Alexander-Hjelm** [comment]
Relabeled as support issue due to lack of reply
