### ISSUE TITLE
Failed to get Azure DevOps/TFS project '<projectName>'

### ISSUE THREAD

**Issue by Jnaneshnayak** [solidify/jira-azuredevops-migrator#70]
Need help. it fails when I try to import the Project data when there is no project created in the Azure DevOps.
Does the script have the functionality to create Project automatically when not found?

**On Console**
 
[W][19:10:28] Project '<ProjectName>' does not exist.
**Would you like to create one? (Y/N)**
y[I][19:10:31] Creating project '<ProjectName>'.
[E][19:10:31] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at WorkItemImport.Agent.<CreateProject>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WorkItemImport.Agent.<GetOrCreateProjectAsync>d__41.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at WorkItemImport.Agent.Initialize(MigrationContext context, Settings settings)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at WorkItemImport.Agent.<CreateProject>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WorkItemImport.Agent.<GetOrCreateProjectAsync>d__41.MoveNext()<---
:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at WorkItemImport.Agent.Initialize(MigrationContext context, Settings settings)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh)
[I][19:10:31] Import complete. Imported 0 items, 0 revisions (2 errors, 1 warnings) in 00:00:04.

**Log file Info**
[Microsoft.TeamFoundation.Core.WebApi.ProjectDoesNotExistWithNameException] Microsoft.TeamFoundation.Core.WebApi.ProjectDoesNotExistWithNameException: TF200016: The following project does not exist: <ProjectName>. Verify that the name of the project is correct and that the project exists on the specified Azure DevOps Server.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WorkItemImport.Agent.<GetOrCreateProjectAsync>d__41.MoveNext():
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WorkItemImport.Agent.<GetOrCreateProjectAsync>d__41.MoveNext()

**Comment by MOlausson** [comment]
@Jnaneshnayak, the tool can create a new Azure DevOps project if the one speficied in the config file does not exist. Looking at your log it looks like you haven't specified the target-project property, make sure it's set to the name you want the new project to have.

**Comment by Jnaneshnayak** [comment]
@MOlausson Thanks for your quick response

My config file looks like this, let me know if I am doing anything wrong.

`{
  "source-project": "Jira-abc",
  "target-project": "abc",
  "query": "project = Jira-abc",
  "workspace": "C:\\Temp\\JiraExport\\",
  "epic-link-field": "Epic Link",
  "sprint-field": "Sprint",
  "download-options": 7,
  "batch-size": 20,
  "log-level": "Debug",
  "attachment-folder": "Attachments",
  "user-mapping-file": "users.txt",
  "base-area-path": "",
  "base-iteration-path": "",
  "ignore-failed-links": true,
  "process-template": "Agile",`

**Comment by MOlausson** [comment]
@Jnaneshnayak sorry for the slow response, I couldn't repro this. Were you able to move forward? I'll put this under review/observation for now.

**Comment by MOlausson** [comment]
Haven't seen this happen unless there's a config error. Closing.
