### ISSUE TITLE
Failed to retrieve issues and 500 error

### ISSUE THREAD

**Issue by jstras17** [solidify/jira-azuredevops-migrator#710]
**Describe the problem**
Running jira-export getting a 'Failed to retrieve issues' error along with 500 error

**To Reproduce**
Running jira-export getting a 'Failed to retrieve issues' error along with 500 error

**Tool version**
 - Version of the jira-azuredevops-migrator tool 3.0.319

**Attachments**

LM.json and jira-export-log attached

**Screenshots**
[E][13:19:55] Failed to retrieve issues
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 500. Response Content: {"errorMessages":["Internal server error"],"errors":{}}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.<EnumerateIssues>d__26.MoveNext()
---> (Inner Exception #0) System.InvalidOperationException: Response Status Code: 500. Response Content: {"errorMessages":["Internal server error"],"errors":{}}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()<---
: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.<EnumerateIssues>d__26.MoveNext()
[LM - Copy.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10817884/LM.-.Copy.json.txt)
[jira-export-log-230223-132903.txt](https://github.com/solidify/jira-azuredevops-migrator/files/10817886/jira-export-log-230223-132903.txt)

**Comment by jstras17** [comment]
JIRA Formatting issue in Filter, related to 4 Issues

Closing for now
