### ISSUE TITLE
A potentially dangerous Request.Path value was detected from the client (:).

### ISSUE THREAD

**Issue by ACLF2406** [solidify/jira-azuredevops-migrator#743]
### Discussed in https://github.com/solidify/jira-azuredevops-migrator/discussions/650

<div type='discussions-op-text'>

<sup>Originally posted by **testsanjay1** December  8, 2022</sup>
[I][19:49:29] Connecting to Azure DevOps/TFS...
[E][19:49:30] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: A potentially dangerous Request.Path value was detected from the client (:).
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at WorkItemImport.WitClientWrapper..ctor(String collectionUri, String project, String personalAccessToken)
   at WorkItemImport.Agent.Initialize(MigrationContext context, Settings settings)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
---> (Inner Exception #0) Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: A potentially dangerous Request.Path value was detected from the client (:).
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext()<---
: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at WorkItemImport.WitClientWrapper..ctor(String collectionUri, String project, String personalAccessToken)
   at WorkItemImport.Agent.Initialize(MigrationContext context, Settings settings)
   at WorkItemImport.ImportCommandLine.ExecuteMigration(CommandOption token, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
[I][19:49:31] Import complete. Imported 0 items, 0 revisions (1 errors, 0 warnings) in 00:00:02.
</div>

**Comment by Alexander-Hjelm** [comment]
@ACLF2406 Please attach you configuration file and the full import log if possible

Issue in the WitClientWrapper constructor:

https://github.com/solidify/jira-azuredevops-migrator/blob/e11a1258c6d5684dd5e6f35c4f823e070596665d/src/WorkItemMigrator/WorkItemImport/WitClient/WitClientWrapper.cs#L25-L32
