### ISSUE TITLE
Error when trying to import to AzureDevOps

### ISSUE THREAD

**Issue by macdonald-keith-vmware** [solidify/jira-azuredevops-migrator#755]
I am attempting to import the Jira work items I extracted to an on-premise AzureDevops server instance

`wi-import` --token XXXXX --url **http**://<serverName>/<CollectionName> --config myconfig-agile.json --force

The log indicates an exception is generated:
[I][15:10:44] Connecting to Azure DevOps/TFS...
[E][15:10:44] Unexpected migration error.
[System.InvalidOperationException] System.InvalidOperationException: **Basic authentication requires a secure connection to the server**.
   at Microsoft.VisualStudio.Services.Common.VssBasicCredential.OnCreateTokenProvider(Uri serverUrl, IHttpResponse response)
   at Microsoft.VisualStudio.Services.Common.IssuedTokenCredential.CreateTokenProvider(Uri serverUrl, IHttpResponse response, IssuedToken failedToken)
   at Microsoft.VisualStudio.Services.Common.VssCredentials.TryGetTokenProvider(Uri serverUrl, IssuedTokenProvider& provider)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()

I have validated the token is correct and has appropriate permissions. Is the problem because the server is using http instead of https?

**Tool version**
 - v3.0.115

**Attachments**
[import.log](https://github.com/solidify/jira-azuredevops-migrator/files/11222204/import.log)

**Comment by Alexander-Hjelm** [comment]
I think BasicAuthCredential requires https://. Running the migrator over an unencrypted connection should be something to consider, maybe. I'll mark this issue as a feature request.

The question is why you would need to run ADO Server unencrypted in the first place?

**Comment by Alexander-Hjelm** [comment]
Can be fixed by using VssClientCredentials: https://stackoverflow.com/questions/61571032/basic-authentication-requires-a-secure-connection-to-the-server-in-tfs
