### ISSUE TITLE
"Unexpected migration error" encountered in Jira Exporter v3.0.174

### ISSUE THREAD

**Issue by AnthonyRobinson** [solidify/jira-azuredevops-migrator#836]
**Describe the problem**

- Performing an export with v3.0.174, I encountered the following error

```
[E][13:38:18] Unexpected migration error.
[System.NullReferenceException] System.NullReferenceException: Object reference not set to an instance of an object.
   at JiraExport.JiraItem.BuildRevisions(JiraItem jiraItem, IJiraProvider jiraProvider)
   at JiraExport.JiraItem.CreateFromRest(String issueKey, IJiraProvider jiraProvider)
   at JiraExport.JiraProvider.<EnumerateIssues>d__26.MoveNext()
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical):
   at JiraExport.JiraItem.BuildRevisions(JiraItem jiraItem, IJiraProvider jiraProvider)
   at JiraExport.JiraItem.CreateFromRest(String issueKey, IJiraProvider jiraProvider)
   at JiraExport.JiraProvider.<EnumerateIssues>d__26.MoveNext()
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical)
```
- Rolling back to v3.0.159, an export of the same Project/config succeeds 

**To Reproduce**

- Download "https://github.com/solidify/jira-azuredevops-migrator/releases/download/v3.0.174/jira-azuredevops-migrator-3.0.174.zip" 
- Unzip and install

**Tool version**

 - v3.0.174
 
**Attachments**

Please attach the following files:

[jira-export-log-230823-133809.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12423226/jira-export-log-230823-133809.txt)

[config_DBDEV.json.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12423245/config_DBDEV.json.txt)

**Comment by Alexander-Hjelm** [comment]
Tried your config, but was unsuccessful in reproducing the bug.

@AnthonyRobinson Would it be possible for you to build and run the project yourself? In that case you could set a breakpoint inside the method `JiraExport.JiraItem.BuildRevisions(JiraItem jiraItem, IJiraProvider jiraProvider)` and provide us with more information about what variable exactly triggers the NullRefException

**Comment by Alexander-Hjelm** [comment]
Yep, makes sense. Probably didn't test that one extensively enough. Will apply a fix now.

**Comment by Alexander-Hjelm** [comment]
Thanks for debugging! @AnthonyRobinson

**Comment by Alexander-Hjelm** [comment]
Created a fix and deployed https://github.com/solidify/jira-azuredevops-migrator/releases/tag/v3.0.178

Let me know if the issue persists!

**Comment by Alexander-Hjelm** [comment]
Closing in lack of response. Reopen if issue persists.
