### ISSUE TITLE
Getting issue in solidify while importing to Azure DevOps

### ISSUE THREAD

**Issue by sabhinandan** [solidify/jira-azuredevops-migrator#838]
Hello Team,

Getting below issue while migrating from JIRA to Azure DevOps

[I][13:15:29] Connecting to Azure DevOps/TFS...
[E][13:15:29] Unexpected migration error.
[Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException] Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Page not found.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Tool version**
 - Version of the jira-azuredevops-migrator tool [jira-azuredevops-migrator-3.0.159]

**Attachments**

Please attach the following files:

- config.json (It was not taking json so changed it to txt)
[config-basic.txt](https://github.com/solidify/jira-azuredevops-migrator/fil
[wi-import-log-230825-131529.txt](https://github.com/solidify/jira-azuredevops-migrator/files/12436928/wi-import-log-230825-131529.txt)
es/12436926/config-basic.txt)

- wi-import-log.txt

Attached is wi import logs and config.json file. 
Please note export is done successfully, facing issue while import.

I created a test azure devops account and created new Personal Access Token
Using command
wi-import --token <Personal Access Token> --url https://dev.azure.com/abhinandanmaheshwari/AzureDemoProject --config config.json --force

**Comment by Alexander-Hjelm** [comment]
The --url parameter should be the URL of the ADO organization, not the project. I will update the documentation
