### ISSUE TITLE
User mapping file cannot have empty lines

### ISSUE THREAD

**Issue by ValekMal** [solidify/jira-azuredevops-migrator#86]
When an empty line (CRLF) is inserted in the user mapping file, the jira-export fails with the below message.
Maybe need to tolerate empty lines.

[E][16:50:05] Unexpected migration error.
[System.IndexOutOfRangeException] System.IndexOutOfRangeException: **Index was outside the bounds of the array.**
   at Migration.Common.BaseMapper`1.ParseUserMappings(String userMappingPath)
   at Migration.Common.BaseMapper`1..ctor(String userMappingPath)
   at JiraExport.JiraMapper..ctor(JiraProvider jiraProvider, ConfigJson config)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh):
   at Migration.Common.BaseMapper`1.ParseUserMappings(String userMappingPath)
   at Migration.Common.BaseMapper`1..ctor(String userMappingPath)
   at JiraExport.JiraMapper..ctor(JiraProvider jiraProvider, ConfigJson config)
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh)

**Comment by MOlausson** [comment]
Thanks for reporting @ValekMal, this should be fixed.
