### ISSUE TITLE
Should return non zero exit code for export failures

### ISSUE THREAD

**Issue by wallymathieu** [solidify/jira-azuredevops-migrator#872]
**Describe the problem**

As a user of the tool I would expect that the tool returns a non zero exit code when the export fails (for instance due to a timeout issue).

**To Reproduce**

1. Export JIRA issues from a JIRA server  
2. Throttle the connection to the JIRA server  
3. If the throttled connection is sufficiently slow you should be able to get a "Error Message: Operation timed out" from  `Atlassian.Jira.Remote.IssueService`

**Tool version**
 - Version of the jira-azuredevops-migrator tool v3.0.186

**Attachments**

```
[E][13:31:20] Unexpected migration error.
[System.AggregateException] System.AggregateException: One or more errors occurred. (Error Message: Operation timed out (someserver.com:443))
 ---> System.InvalidOperationException: Error Message: Operation timed out (someserver.com:443)
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.ExecuteRequestAsync(Method method, String resource, Object requestBody, CancellationToken token)
   at Atlassian.Jira.Remote.IssueService.GetCommentsAsync(String issueKey, CommentQueryOptions options, CancellationToken token)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at JiraExport.JiraProvider.GetCommentsByItemKey(String itemKey) in /Users/mathieu/src/work/jira-azuredevops-migrator/src/WorkItemMigrator/JiraExport/JiraProvider.cs:line 90
   at JiraExport.JiraItem.BuildCommentRevisions(JiraItem jiraItem, IJiraProvider jiraProvider) in /Users/mathieu/src/work/jira-azuredevops-migrator/src/WorkItemMigrator/JiraExport/JiraItem.cs:line 220
   at JiraExport.JiraItem.BuildRevisions(JiraItem jiraItem, IJiraProvider jiraProvider) in /Users/mathieu/src/work/jira-azuredevops-migrator/src/WorkItemMigrator/JiraExport/JiraItem.cs:line 117
   at JiraExport.JiraItem.CreateFromRest(String issueKey, IJiraProvider jiraProvider) in /Users/mathieu/src/work/jira-azuredevops-migrator/src/WorkItemMigrator/JiraExport/JiraItem.cs:line 27
   at JiraExport.JiraProvider.ProcessItem(String issueKey, HashSet`1 skipList) in /Users/mathieu/src/work/jira-azuredevops-migrator/src/WorkItemMigrator/JiraExport/JiraProvider.cs:line 108
   at JiraExport.JiraProvider.EnumerateIssues(String jql, HashSet`1 skipList, DownloadOptions downloadOptions)+MoveNext() in /Users/mathieu/src/work/jira-azuredevops-migrator/src/WorkItemMigrator/JiraExport/JiraProvider.cs:line 235
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical) in /Users/mathieu/src/work/jira-azuredevops-migrator/src/WorkItemMigrator/JiraExport/JiraCommandLine.cs:line 123: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at JiraExport.JiraProvider.GetCommentsByItemKey(String itemKey) in /Users/mathieu/src/work/jira-azuredevops-migrator/src/WorkItemMigrator/JiraExport/JiraProvider.cs:line 90
   at JiraExport.JiraItem.BuildCommentRevisions(JiraItem jiraItem, IJiraProvider jiraProvider) in /Users/mathieu/src/work/jira-azuredevops-migrator/src/WorkItemMigrator/JiraExport/JiraItem.cs:line 220
   at JiraExport.JiraItem.BuildRevisions(JiraItem jiraItem, IJiraProvider jiraProvider) in /Users/mathieu/src/work/jira-azuredevops-migrator/src/WorkItemMigrator/JiraExport/JiraItem.cs:line 117
   at JiraExport.JiraItem.CreateFromRest(String issueKey, IJiraProvider jiraProvider) in /Users/mathieu/src/work/jira-azuredevops-migrator/src/WorkItemMigrator/JiraExport/JiraItem.cs:line 27
   at JiraExport.JiraProvider.ProcessItem(String issueKey, HashSet`1 skipList) in /Users/mathieu/src/work/jira-azuredevops-migrator/src/WorkItemMigrator/JiraExport/JiraProvider.cs:line 108
   at JiraExport.JiraProvider.EnumerateIssues(String jql, HashSet`1 skipList, DownloadOptions downloadOptions)+MoveNext() in /Users/mathieu/src/work/jira-azuredevops-migrator/src/WorkItemMigrator/JiraExport/JiraProvider.cs:line 235
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh, CommandOption continueOnCritical) in /Users/mathieu/src/work/jira-azuredevops-migrator/src/WorkItemMigrator/JiraExport/JiraCommandLine.cs:line 123
[I][13:31:20] Export complete. Exported 48324 items (82 errors, 24 warnings) in 02:10:21.
```

**Comment by Alexander-Hjelm** [comment]
What is the issue here? Do you mean that JiraExport.exe returns code 0 even if the tool fails? Or that the error message should describe more clearly that the tool canceled due to timeout? 🙂

**Comment by wallymathieu** [comment]
That the tool returns an exit code that indicates success even though it clearly fails to export due to a timeout.

**Comment by wallymathieu** [comment]
I guess the last message is sort of confused since it did not do all that it says. The amount of items processed are actually far less.

**Comment by Alexander-Hjelm** [comment]
Ok perfect. Will keep this on the backlog, and work on a fix when I get around to it. Atm there are more pressing bugs :)

**Comment by Alexander-Hjelm** [comment]
@wallymathieu PR created. Give it a try if it's possible for you, and let me know the result!
