### ISSUE TITLE
Jira-azuredevops-migrator 3.0.335 random attachment issue

### ISSUE THREAD

**Issue by angierieger77** [solidify/jira-azuredevops-migrator#967]
Error in the log file

[System.IO.DirectoryNotFoundException] System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Temp\Attachments\27586\CoreWirelessRules_20July2020.xlsx'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at WorkItemImport.WitClientWrapper.CreateAttachment(WiAttachment attachment)
   at WorkItemImport.WitClientUtils.AddSingleAttachmentToWorkItemAndSave(WiAttachment att, WorkItem wi, Settings settings, Nullable`1 changedDate, String changedBy)
   at WorkItemImport.WitClientUtils.SaveWorkItemAttachments(WiRevision rev, WorkItem wi, Settings settings)
   at WorkItemImport.Agent.ImportRevision(WiRevision rev, WorkItem wi, Settings settings): 
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at WorkItemImport.WitClientWrapper.CreateAttachment(WiAttachment attachment)
   at WorkItemImport.WitClientUtils.AddSingleAttachmentToWorkItemAndSave(WiAttachment att, WorkItem wi, Settings settings, Nullable`1 changedDate, String changedBy)
   at WorkItemImport.WitClientUtils.SaveWorkItemAttachments(WiRevision rev, WorkItem wi, Settings settings)
   at WorkItemImport.Agent.ImportRevision(WiRevision rev, WorkItem wi, Settings settings)

**Tool version**
 jira-azuredevops-migrator-3.0.335

**Attachments**

Please attach the following files:
[wi-import-log-240116-144857.txt](https://github.com/solidify/jira-azuredevops-migrator/files/13979799/wi-import-log-240116-144857.txt)

![attachment_Folder_file_27586](https://github.com/solidify/jira-azuredevops-migrator/assets/157050085/dde0dfab-fc34-4082-9df2-5b3851bb4208)

**Comment by angierieger77** [comment]
It looks like I have 34 of these attachment issues - I verified that the path exists and the file exists, but cannot determine why the attachment would not import.  Please help, thanks!

**Comment by Alexander-Hjelm** [comment]
Maybe something to do with Windows folder permissions? Did you check that?

**Comment by angierieger77** [comment]
@Alexander-Hjelm yes I have checked the folder permissions - there's hundreds of attachments - and only these 34 did not migrate and had the error - any other thoughts / ideas what may be going on?
