### ISSUE TITLE
Failed to get item count using query: 'project = "KAN" ORDER BY created DESC'

### ISSUE THREAD

**Issue by swahithsoma** [solidify/jira-azuredevops-migrator#979]
Hi team

when we are trying to export the jira. we are get the below error.

[E][13:59:22] Failed to get item count using query: 'project = "KAN" ORDER BY created DESC'
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'KAN' does not exist for the field 'project'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
---> (Inner Exception #0) System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'KAN' does not exist for the field 'project'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()<---
:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)

and pls find the .json file below and error screenshot, cloud you give me any solution on it. ASSP.
 
[config.json](https://github.com/solidify/jira-azuredevops-migrator/files/14176784/config.json)
<img width="949" alt="Screenshot 2024-02-06 140303" src="https://github.com/solidify/jira-azuredevops-migrator/assets/116541646/671ee5ac-76f7-4aaf-9934-037e37364544">

Thanks
Sagar.

**Comment by Alexander-Hjelm** [comment]
Either there is no project with the key "KAN" or there is an authorization issue :)

**Comment by eplnde** [comment]
The syntax on the query looks strange, why try to escape the " ?
  "query": "project = \"KAN\" ORDER BY created DESC",

I bet that filter fails for you in Jira as well...

Try with
  "query": "project=KAN ORDER BY created DESC",

**Comment by swahithsoma** [comment]
Hi team 

Just I tried  "query": "project=KAN ORDER BY created DESC",
but getting same error, pls find the logs.

Jira Exporter v3.0.346
Copyright (c) Solidify
Wow, there's a newer release out (v3.0.350)! We recommend downloading it for latest features and fixes.
[I][16:00:01] Connecting to Jira...
[I][16:00:02] Retrieving Jira fields...
[I][16:00:02] Retrieving Jira link types...
[E][16:00:03] Failed to get item count using query: 'project=KAN ORDER BY created ASC'
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'KAN' does not exist for the field 'project'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
---> (Inner Exception #0) System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'KAN' does not exist for the field 'project'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()<---
:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
[I][16:00:04] Export started. Selecting 0 items.
[W][16:00:06] Epic link field missing for config field 'Epic Link'.
[W][16:00:06] Sprint link field missing for config field 'Sprint'.
[W][16:00:06] User mapping file 'C:\Users\swahith.soma\Documents\jira-Azdo\users.txt' not found, ignoring mapping user identities.
[I][16:00:06] Initializing Jira field mapping...
[W][16:00:06] Could not find the field id for 'Sprint', please check the field mapping!
[W][16:00:06] Could not find the field id for 'Story Points', please check the field mapping!
[E][16:00:07] Failed to retrieve issues
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'KAN' does not exist for the field 'project'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.<EnumerateIssues>d__30.MoveNext()
---> (Inner Exception #0) System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'KAN' does not exist for the field 'project'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()<---
:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.<EnumerateIssues>d__30.MoveNext()
[I][16:00:07] Export complete. Exported 0 items (2 errors, 5 warnings) in 00:00:05.

**Comment by swahithsoma** [comment]
[jira-export-log-240206-163554.txt](https://github.com/solidify/jira-azuredevops-migrator/files/14178691/jira-export-log-240206-163554.txt)

**Comment by swahithsoma** [comment]
> Either there is no project with the key "KAN" or there is an authorization issue :)

Hi  @Alexander-Hjelm 

**jira-export -u swahiht****@gmail.com -p ******** --url https://swahith******.atlassian.net --config config.json –force**
can pls confirm above comment is correct or not?
can we use the account mail-id as username, 
**Note: for privacy purpose we hided the passwd and mail**  

Thanks
Swahith

**Comment by Alexander-Hjelm** [comment]
See this page for common issues and remedies related to authentication against Jira: https://github.com/solidify/jira-azuredevops-migrator/blob/master/docs/faq.md#2-why-i-am-getting-unauthorized-exception-when-running-the-export

**Comment by gripley151** [comment]
> > Either there is no project with the key "KAN" or there is an authorization issue :)
> 
> Hi @Alexander-Hjelm
> 
> jira-export -u swahiht****@gmail.com -p ******** --url https://swahith******.atlassian.net --config config.json –force can pls confirm above command is correct or not? can we use the account mail-id as username, **Note: for privacy purpose we hided the passwd and mail**
> 
> Thanks Swahith

I am also having issues and with identical problem Swahith is explaining.  I'll be watching this thread closely to a solution.  I am reading the common issues pages and so far without success.
Gregg

**Comment by gripley151** [comment]
FYI - After messing around with the various credentials and options of which user name and password, etc, I was able to make a good connection and everything is working fine.  In my case, it's a cloud-based Jira and the username was my full email address and the password -p <token> was the token.  I did not use the token <-t> parameter.

**Comment by marek-dziechciarz** [comment]
same for me, using token as a password solves the problem
