### ISSUE TITLE
Story Points or Effort cannot be changed to zero (0) in the change log

### ISSUE THREAD

**Issue by ValekMal** [solidify/jira-azuredevops-migrator#98]
When in JIRA someone changed story points or effort from something to zero (0), export works okay, but the import fails with the message

[I][16:29:16] Field: 'Story Points', Status: 'InvalidType', Value: ''
[E][16:29:16] Failed to import revisions for '268'.
[Microsoft.TeamFoundation.WorkItemTracking.Client.ValidationException] Microsoft.TeamFoundation.WorkItemTracking.Client.ValidationException: TF237124: Work Item is not ready to save
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.Save(SaveFlags saveFlags)
   at WorkItemImport.Agent.SaveWorkItem(WiRevision rev, WorkItem newWorkItem)
   at WorkItemImport.Agent.ImportRevision(WiRevision rev, WorkItem wi):
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.Save(SaveFlags saveFlags)
   at WorkItemImport.Agent.SaveWorkItem(WiRevision rev, WorkItem newWorkItem)
   at WorkItemImport.Agent.ImportRevision(WiRevision rev, WorkItem wi)

**Comment by madkoo** [comment]
@ValekMal are you still stuck with this issue? I tried to repro the problem, by changing the Stroy Points to 0 in Jira and then doing the Export-Import. I was not able to get the exception you did.
If you are still stuck can you provide more context what you did and share the import log file.

**Comment by ValekMal** [comment]
I moved off the project. Sorry not using the tool at this stage and cannot confirm.
