### ISSUE TITLE
jira-export- not able to fetch the project name, even if it exist

### ISSUE THREAD

**Issue by abhilashagowda4241** [solidify/jira-azuredevops-migrator#997]
Command: jira-export -u user.name -p XXXXX --url jiraURL --config config-scrum.json --force
Error:
Jira Exporter v3.0.364
Copyright (c) Solidify
[I][19:53:47] Connecting to Jira...
[I][19:53:47] Retrieving Jira fields...
[I][19:53:47] Retrieving Jira link types...
[E][19:53:48] Failed to get item count using query: 'project = project1 ORDER BY Rank ASC'
[System.AggregateException] System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Response Status Code: 400. Response Content: {"errorMessages":["The value 'project1' does not exist for the field 'project'.","Not able to sort using field 'Rank'."],"warningMessages":[]}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JiraExport.JiraProvider.GetItemCount(String jql)
<img width="171" alt="Screenshot 2024-03-14 200709" src="https://github.com/solidify/jira-azuredevops-migrator/assets/83212984/33eae60d-2194-464d-ab82-e527637f2f95">

I tried with username = email address, password = API Token but it didnt work for me. Same JQL query is working in jira. Can you please help with this asap

**Comment by Alexander-Hjelm** [comment]
Would it be possible for you to try the following as a workaround?
- Try another project
- Or steal the api token of another user with higher permissions and try again. The other user can revoke their token after the experiment.

**Comment by abhilashagowda4241** [comment]
I have tried multiple users, with multiple projects still getting the same error
<img width="848" alt="Screenshot 2024-03-14 210803" src="https://github.com/solidify/jira-azuredevops-migrator/assets/83212984/42200e09-7f88-4be0-bbb0-d2381f9d0eff">

**Comment by Alexander-Hjelm** [comment]
Ok! Would it be possible to set up the same query in cUrl, Postman or a similar software?

Here is the query:

```
https://jira.xxx.com/rest/api/3/search?jql=project=PROJECTKEY

Authorization: Basic {base64EncodedCredentials}
```

Replace `{base64EncodedCredentials}` with a base64-encoded string in the format `username:api_token`

**Comment by abhilashagowda4241** [comment]
I am using command prompt, i tried with the above also, please help me with this command 
jira-export -u abhilashadxxxxxx@gmail.com -p api --url https://abhilashadxxxxxxxx.atlassian.net/--config Samples\config-scrum.json --force
<img width="401" alt="Screenshot 2024-03-14 211953" src="https://github.com/solidify/jira-azuredevops-migrator/assets/83212984/c50d34f5-1bbb-4b29-bc46-0b199f307ab0">

**Comment by Alexander-Hjelm** [comment]
I'm not sure then, other than all of the answers I have suggested, among which one or another have seemed to work for most people so far.

Would it be possible to get help from the Atlassian Support maybe?
